version: '3.9'

volumes:
  db-data:

services:
  postgres:
    image: 'postgres:latest'
    container_name: rest-db
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    networks:
      - nestjs
    volumes:
      - db-data:/var/lib/postgresql/rest-db/data

networks:
  nestjs:
